## Basic Info 2.4 이후 표준 적용
spring:
  profiles:
    active: prod
    group:
        dev:
            - common
        prod:
            - common

---
spring:
  config:
    activate:
      on-profile: common
  cache:
    ehcache:
      config: cache/ehcache.xml
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+9"
  mail:
    host: smtp.dooray.com
    port: 465
    username: skkim@aimslas.com
    password: autocapture00!
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            required: true
            enable: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v2/**
file:
  upload-dir: /home/hana/images/enc/hana/phone

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hana?characterEncoding=utf8mb4
    username: root
    password: autocapture00!
    hikari:
      poolName: Hikari
      maximum-pool-size: 50
      minimum-idle: 2
      max-lifetime: 30000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: false
logging:
  pattern:
    console: "%d %-5level %logger[%line] : %msg%n"
    file: "%d %-5level [%thread] %logger{36}[%line] : %msg%n"
  level:
    root: info
    com.aimskr.ac2: debug
  file:
    name: logs/application-info.log
server:
  port: 44306
  http:
    port: 8086
  error:
    include-exception: true
    include-stacktrace: always
  ssl:
    enabled: true
    key-store: "/etc/httpd/conf/cert/autocapture.jks"
    key-store-type: "JKS"
    key-store-password: autocapture
    key-alias: 1
    trust-store: "/etc/httpd/conf/cert/autocapture.ts"
    trust-store-password: autocapture
autocapture: # 외부 연계르 위한 API 주소, AutocaptureConfig.java에서 관리
  sftpip: 10.1.201.72
  sftpPort: 22
  sftpUser: aimsftp
  sftpKey:
  sftpPwd: dpdlatm1!
  sftpPath: /files/ftpfile/aims/send/
  apiServer: https://dgate.hanainsure.co.kr:31010/aims/ProcResult
#  apiServer: https://dev.aimskr.com:44306/hana/v1/mock
  resultPath:
  credential:
  qaPath:
  frontUrl: https://dev.aimskr.com:4436
filepath: # 이미지 파일 처리를 위한 설정 정보
  originDir: /home/hana/images/enc/hana/origin
  acDir: /home/hana/images/enc/hana/ac
  visorgDir: /home/hana/images/enc/hana/visorg
  visDir: /home/hana/images/enc/hana/vis
  reportDir: /home/hana/images/enc/hana/report
control:
  autoReturn: false
  dupCheck: false
  requestValidation: false
  alertMode: true
  alertEmail: "skkim@aimslas.com"
  errorEmail:
    - "skkim@aimslas.com"

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.213.96:3306/hana?characterEncoding=utf8mb4
    username: root
    password: autocapture00!
    hikari:
      poolName: Hikari
      maximum-pool-size: 50
      minimum-idle: 2
      max-lifetime: 30000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: false
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    com.aimskr.ac2: debug
  file:
    name: logs/application-info.log
server:
  port: 44306
  http:
    port: 8086
  error:
    include-exception: true
    include-stacktrace: always
  ssl:
    enabled: true
    key-store: "/etc/httpd/conf/cert/autocapture.jks"
    key-store-type: "JKS"
    key-store-password: autocapture
    key-alias: 1
    trust-store: "/etc/httpd/conf/cert/autocapture.ts"
    trust-store-password: autocapture
autocapture: # 외부 연계르 위한 API 주소, AutocaptureConfig.java에서 관리
  sftpip: 10.1.200.92
  sftpPort: 22
  sftpUser: aimsftp
  sftpKey:
  sftpPwd: dpdlatm1!
  sftpPath: /files/ftpfile/aims/send/
  apiServer: https://gate.hanainsure.co.kr:31010/aims/ProcResult
  resultPath:
  credential:
  qaPath:
  frontUrl: https://capture.aimskr.com:4436
filepath: # 이미지 파일 처리를 위한 설정 정보
  originDir: /home/hana/images/enc/hana/origin
  acDir: /home/hana/images/enc/hana/ac
  visorgDir: /home/hana/images/enc/hana/visorg
  visDir: /home/hana/images/enc/hana/vis
  reportDir: /home/hana/images/enc/hana/report
control:
  autoReturn: false
  dupCheck: true
  requestValidation: true
  alertMode: true
  alertEmail: "hjpark@aimslas.com"
  errorEmail:
    - "skkim@aimslas.com"
    - "jhlee@aimslas.com"
